---
version: 0.0.3
author: GOOSLEENG

paths:
  models: 
    mediapipe: './models/mediapipe/'
    other: './models/other/'
  utils: utils/
  media: media/
  landmarks_result: media/keypoints
  logs: logs/
